name: Build and push Docker images

on: push

jobs:
  build_voila:
    name: Build and Push jh-voila-oauth-singleuser
    runs-on: ubuntu-18.04
    steps:
      - name: Step jh-voila-oauth-singleuser 
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          path: voila
          repository: ideonate/jh-voila-oauth-singleuser
          build_args: BASE_REPO=jupyter/singleuser:1.2
          tag_with_ref: true
          tag_with_sha: true

  build_all:
    name: Build and Push containds-all-basic
    runs-on: ubuntu-18.04
    steps:
      - name: Step containds-all-basic 
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          path: all
          repository: ideonate/containds-all-basic
          build_args: BASE_REPO=ideonate/jh-voila-oauth-singleuser:${{ github.ref }}
          tag_with_ref: true
          tag_with_sha: true



